packages:
  - './programs/cli'
  - './programs/create'
  - './programs/develop'
  - './examples/*'
  - './examples-v2/*'
  # Ignore dist folders used for testing
  - "!programs/cli/dist"
  - "!programs/create/dist"
  - "!programs/develop/dist"
  